channels:
  - conda-forge

dependencies:
- python=3.12.0
- pip<=22.3.1

  - pip

      - numpy
      - pandas==2.3.5
      - scikit-learn==1.8.0
      - mlflow==2.19.0
      - joblib==1.5.2

name: mlflow-env
